ALTER TABLE onus ADD COLUMN IF NOT EXISTS mobile2 VARCHAR(64) DEFAULT '';
ALTER TABLE onus ADD COLUMN IF NOT EXISTS govt_id_type VARCHAR(16) DEFAULT '';
ALTER TABLE onus ADD COLUMN IF NOT EXISTS govt_id_number VARCHAR(64) DEFAULT '';
ALTER TABLE onus ADD COLUMN IF NOT EXISTS dob VARCHAR(16) DEFAULT '';
ALTER TABLE onus ADD COLUMN IF NOT EXISTS landmark VARCHAR(256) DEFAULT '';
