ALTER TABLE onus ADD COLUMN IF NOT EXISTS vendor VARCHAR(128) DEFAULT '';
ALTER TABLE onus ADD COLUMN IF NOT EXISTS sw_version VARCHAR(128) DEFAULT '';
ALTER TABLE onus ADD COLUMN IF NOT EXISTS lan_status VARCHAR(16) DEFAULT '';
ALTER TABLE onus ADD COLUMN IF NOT EXISTS bw_in BIGINT;
ALTER TABLE onus ADD COLUMN IF NOT EXISTS bw_out BIGINT;
